export const SHOP_ITEMS = {
  themes: [
    { id: 'light', name: 'Light Mode', levelReq: 1, cssClass: 'bg-zinc-100 border-zinc-300' },
    { id: 'dark', name: 'Dark Mode', levelReq: 1, cssClass: 'bg-zinc-900 border-zinc-700' },
    { id: 'midnight-blue', name: 'Midnight Blue', levelReq: 5, cssClass: 'bg-orange-950 border-orange-800' },
    { id: 'forest-green', name: 'Forest Green', levelReq: 10, cssClass: 'bg-emerald-950 border-emerald-800' },
    { id: 'ocean-breeze', name: 'Ocean Breeze', levelReq: 15, cssClass: 'bg-orange-900 border-orange-700' },
    { id: 'sunset-orange', name: 'Sunset Orange', levelReq: 20, cssClass: 'bg-orange-900 border-orange-700' },
    { id: 'cyberpunk-neon', name: 'Cyberpunk Neon', levelReq: 30, cssClass: 'bg-fuchsia-900 border-fuchsia-700' },
    { id: 'vaporwave-purple', name: 'Vaporwave Purple', levelReq: 40, cssClass: 'bg-violet-900 border-violet-700' },
    { id: 'obsidian-gold', name: 'Obsidian Gold', levelReq: 50, cssClass: 'bg-yellow-900 border-yellow-700' },
    { id: 'ascended-ruby', name: 'Ascended Ruby', levelReq: 100, cssClass: 'bg-red-950 border-red-800' },
  ],
  emojis: [
    { id: 'skull', emoji: '💀', levelReq: 1 },
    { id: 'rocket', emoji: '🚀', levelReq: 5 },
    { id: 'fox', emoji: '🦊', levelReq: 10 },
    { id: 'zap', emoji: '⚡', levelReq: 15 },
    { id: 'alien', emoji: '👽', levelReq: 20 },
    { id: 'ghost', emoji: '👻', levelReq: 30 },
    { id: 'robot', emoji: '🤖', levelReq: 40 },
    { id: 'dragon', emoji: '🐉', levelReq: 50 },
    { id: 'crown', emoji: '👑', levelReq: 75 },
    { id: 'galaxy', emoji: '🌌', levelReq: 100 },
  ],
  titles: [
    { id: 'novice', name: 'Novice', levelReq: 1 },
    { id: 'beginner', name: 'Beginner', levelReq: 5 },
    { id: 'grinder', name: 'Grinder', levelReq: 10 },
    { id: 'adept', name: 'Adept', levelReq: 15 },
    { id: 'deep-worker', name: 'Deep Worker', levelReq: 20 },
    { id: 'specialist', name: 'Specialist', levelReq: 30 },
    { id: 'master', name: 'Master', levelReq: 40 },
    { id: 'warlord', name: 'Warlord', levelReq: 50 },
    { id: 'legend', name: 'Legend', levelReq: 75 },
    { id: 'emperor', name: 'Emperor', levelReq: 100 },
  ],
  rings: [
    { id: 'basic-white', name: 'Basic White', levelReq: 1, borderClass: 'border-white/40' },
    { id: 'bronze-band', name: 'Bronze Band', levelReq: 10, borderClass: 'border-orange-600/60 shadow-[0_0_20px_rgba(234,88,12,0.4)]' },
    { id: 'silver-glow', name: 'Silver Glow', levelReq: 25, borderClass: 'border-zinc-300/80 shadow-[0_0_25px_rgba(212,212,216,0.6)]' },
    { id: 'gold-aura', name: 'Gold Aura', levelReq: 50, borderClass: 'border-yellow-400 shadow-[0_0_30px_rgba(250,204,21,0.8)]' },
    { id: 'diamond-plasma', name: 'Diamond Plasma', levelReq: 100, borderClass: 'border-orange-300 shadow-[0_0_40px_rgba(103,232,249,1)]' },
  ]
};
